#pragma once


/*
#define BOOT_INIT
#define BOOT_ENTRY_CONDITION (0)


#define USB_CONNECT_PORT LPC_GPIO2
#define USB_CONNECT_PIN 9
//#define USB_CONNECT_INVERT

#define LED_PORT LPC_GPIO2
#define LED_PIN 0

#define USER_START_SECTOR 2
#define MAX_USER_SECTOR 7
*/

/*
#define BOOT_INIT

#define USB_CONNECT_PORT LPC_GPIO1
#define USB_CONNECT_PIN 18
//#define USB_CONNECT_INVERT

#define LED_PORT LPC_GPIO1
#define LED_PIN 14

#define USER_START_SECTOR 1
#define MAX_USER_SECTOR 29

#define BOOT_ENTRY_CONDITION ((LPC_GPIO1->FIOPIN & (1<<19))==0 && (LPC_GPIO1->FIOPIN & (1<<23))==0)

*/

#define BOOT_INIT

#define USB_CONNECT_PORT LPC_GPIO1
#define USB_CONNECT_PIN 18
//#define USB_CONNECT_INVERT

#define P2_10_RESET 1

#define LED_PORT LPC_GPIO0
#define LED_PIN 22

#define USER_START_SECTOR 1
#define MAX_USER_SECTOR 15

#define BOOT_ENTRY_CONDITION ((LPC_GPIO2->FIOPIN & (1<<4))==0)
